language: php

php:
    - "5.6"

env:
    - WP_VERSION=master WP_MULTISITE=0 #Current stable release

# Test WP master, current and previous stable releases on most popular PHP 5.5, 5.6 (w/ multisite enabled for 5.6)
# Test WP master, current and previous stable releases on minimum PHP 5.2 (w/o multisite enabled)
# Test WP current on PHP 5.3, 5.4 (w/o multisite enabled)
# Test WP master on PHP 7.0 and nightly (w/o multisite enabled)

matrix:
  include:
    # current stable release w/ multisite
    - php: "5.6"
      env: WP_VERSION=master WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.5 WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=master WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=4.5 WP_MULTISITE=0
    - php: "nightly"
      env: WP_VERSION=master WP_MULTISITE=0
  allow_failures:
    - php: "nightly"

before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone --depth=1 --branch $WP_VERSION git://develop.git.wordpress.org/ /tmp/wordpress
    - cd ..
    - mv $PLUGIN_SLUG "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - |
        if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
          composer global require "phpunit/phpunit=5.7.*"
        else
          composer global require "phpunit/phpunit=4.8.*"
        fi

script: phpunit

sudo: false
