language: php

php:
    - "5.6"
    - "7.2"
    - "7.3"
    - "7.4"

services:
    - mysql

env:
    - WP_VERSION=latest WP_MULTISITE=0 #Current stable release

# Test WP 5.2 and on PHP 5.6, 7.2, 7.3, and 7.4 (w/ and w/o multisite enabled)

matrix:
  include:
    # current stable release w/ multisite
    - env: WP_VERSION=latest WP_MULTISITE=1
    # n-1 major release
    - php: "5.6"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "7.2"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "7.3"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "7.4"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    - php: "7.2"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    - php: "7.3"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    - php: "7.4"
      env: WP_VERSION=5.2 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export COMPOSER_BIN_DIR="$HOME/.config/composer/vendor/bin"
    - export PATH="$COMPOSER_BIN_DIR:$PATH"
    - |
        if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
          composer global require "phpunit/phpunit=5.7.*"
        fi
    - phpunit --version
    - php --version

script: phpunit

sudo: false
