language: php

php:
    - "5.6"
    - "7.2"
    - "7.3"
    - "7.4"

services:
    - mysql

env:
    - RUN_PHPCS=1 WP_VERSION=latest WP_MULTISITE=0 #Current stable release

# Test WP 5.2 and on PHP 5.6, 7.2, 7.3, and 7.4 (w/ and w/o multisite enabled)

matrix:
  include:
    # current stable release w/ multisite
    - env: WP_VERSION=latest WP_MULTISITE=1
    # n-1 major release
    - php: "5.6"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "7.2"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    - php: "7.3"
      env: WP_VERSION=5.2 WP_MULTISITE=0
    # - skip PHP 7.4 and WP 5.2 (not compatible)
    - php: "5.6"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    - php: "7.2"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    - php: "7.3"
      env: WP_VERSION=5.2 WP_MULTISITE=1
    # - skip PHP 7.4 and WP 5.2 (not compatible)

install:
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer install
      fi

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export COMPOSER_BIN_DIR="$HOME/.config/composer/vendor/bin"
    - export PATH="$COMPOSER_BIN_DIR:$PATH"
    - |
        if [[ ${RUN_PHPCS} == "1" ]]; then
          npm install
        fi
    - |
        if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
          composer global require "phpunit/phpunit=5.7.*"
        fi
    - phpunit --version
    - php --version

script: 
  - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]] && [[ ${RUN_PHPCS} == "1" ]]; then
        bash bin/phpcs-diff.sh
        npm run lint
      fi
  - phpunit

sudo: false
