language: php

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"

env:
    - WP_VERSION=latest WP_MULTISITE=0 #Current stable release

# Test WP 4.8 and on PHP 5.4, 5.5, 5.6, 7.0 and 7.1 (w and w/o multisite enabled)
# Test WP 4.8 and on PHP 5.2 and 5.3 and allow_failures (w and w/o multisite enabled)
# Test WP master on PHP nightly (w/o multisite enabled)

matrix:
  include:
    # current stable release w/ multisite
    - php: "5.2"
      env: WP_VERSION=4.8 WP_MULTISITE=0
      dist: precise
    - php: "5.3"
      env: WP_VERSION=4.8 WP_MULTISITE=0
      dist: precise
    - php: "5.4"
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: "5.5"
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: "7.1"
      env: WP_VERSION=4.8 WP_MULTISITE=0
    - php: "5.2"
      env: WP_VERSION=4.8 WP_MULTISITE=1
      dist: precise
    - php: "5.3"
      env: WP_VERSION=4.8 WP_MULTISITE=1
      dist: precise
    - php: "5.4"
      env: WP_VERSION=4.8 WP_MULTISITE=1
    - php: "5.5"
      env: WP_VERSION=4.8 WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.8 WP_MULTISITE=1
    - php: "7.0"
      env: WP_VERSION=4.8 WP_MULTISITE=1
    - php: "7.1"
      env: WP_VERSION=4.8 WP_MULTISITE=1
    - php: "5.2"
      env: WP_VERSION=4.9 WP_MULTISITE=0
      dist: precise
    - php: "5.3"
      env: WP_VERSION=4.9 WP_MULTISITE=0
      dist: precise
    - php: "5.4"
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: "5.5"
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: "5.6"
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: "7.1"
      env: WP_VERSION=4.9 WP_MULTISITE=0
    - php: "5.2"
      env: WP_VERSION=4.9 WP_MULTISITE=1
      dist: precise
    - php: "5.3"
      env: WP_VERSION=4.9 WP_MULTISITE=1
      dist: precise
    - php: "5.4"
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: "5.5"
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: "5.6"
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: "7.0"
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: "7.1"
      env: WP_VERSION=4.9 WP_MULTISITE=1
    - php: "nightly"
      env: WP_VERSION=latest WP_MULTISITE=0
  allow_failures:
    - php: "nightly"
    - php: "5.2"
    - php: "5.3"

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
        if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
          composer global require "phpunit/phpunit=5.7.*"
        fi
    - phpunit --version
    - php --version

script: phpunit

sudo: false
