name: E2E and JS tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up NodeJS 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build Edit Flow
        run: |
          npm ci
          npm run build

      - name: Install WordPress with wp-env
        run: npm run wp-env start

      - name: Run Lint JS
        run: npm run lint-js

      - name: Run JS tests (Jest)
        run: npm run test-jest

      - name: Run E2E tests
        run: npm run test-e2e
