name: E2E and JS tests

on:
  pull_request:
  push:
    branches-ignore:
      - develop
      - main

# Disable all permissions by default; grant minimal permissions per job
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: E2E and JS tests
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Set up NodeJS 20
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '20'
          cache: npm

      - name: Build Edit Flow
        run: |
          npm ci
          npx playwright install --with-deps chromium
          npm run build

      - name: Install WordPress with wp-env
        run: npm run wp-env start

      - name: Run Lint JS
        run: npm run lint-js

      - name: Run tests
        run: npm run test
