name: E2E and JS tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Build Edit Flow
        run: |
          npm ci
          npm run build

      - name: Install WordPress with wp-env
        run: npm run wp-env start

      - name: Run Lint JS
        run: npm run lint-js

      - name: Run Jest tests
        run: npm run test-jest

      - name: Run E2E tests (1/10)
        run: npm run test-e2e

      - name: Run E2E tests (2/10)
        run: npm run test-e2e

      - name: Run E2E tests (3/10)
        run: npm run test-e2e

      - name: Run E2E tests (4/10)
        run: npm run test-e2e

      - name: Run E2E tests (5/10)
        run: npm run test-e2e

      - name: Run E2E tests (6/10)
        run: npm run test-e2e

      - name: Run E2E tests (7/10)
        run: npm run test-e2e

      - name: Run E2E tests (8/10)
        run: npm run test-e2e

      - name: Run E2E tests (9/10)
        run: npm run test-e2e

      - name: Run E2E tests (10/10)
        run: npm run test-e2e
